update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,24 +32,40 @@ jobs:
             - name: Checkout repository
               uses: actions/checkout@v3
 
-            - name: Install NTP 
-              run: |
-                sudo apt-get update
-                sudo apt-get install -y ntp
-                sudo systemctl enable ntp
-                sudo systemctl start ntp
-
             - name: Run Docker images
               run: |
                 docker run -d --name glpi -p 80:80 ${{ env.glpi }}
 
-            - name: Setup Python Version
-              uses: actions/setup-python@v2
-              with:
-                python-version: 3.8
+            - name: Check container status
+              run: |
+                container_status=$(docker inspect -f '{{.State.Status}}' glpi)
+                if [ $? -eq 0 ]; then
+                  echo -e "\033[92mContainer status: $container_status (OK)\033[0m"
+                else
+                  echo -e "\033[91mContainer status: $container_status (Falha)\033[0m"
+                  exit 1
+                fi
 
-            - name: Execute Python tests
-              run: python ./verify/check.py
+            - name: Check NGINX status in container
+              run: |
+                nginx_status=$(docker exec glpi service nginx status)
+                if [ $? -eq 0 ]; then
+                  echo -e "\033[92mNGINX status: $nginx_status (OK)\033[0m"
+                else
+                  echo -e "\033[91mNGINX status: $nginx_status (Falha)\033[0m"
+                  exit 1
+                fi
+
+            - name: Check PHP-FPM v8.3 status in container
+              run: |
+                php_status=$(docker exec glpi service php8.3-fpm status)
+                if [ $? -eq 0 ]; then
+                  echo -e "\033[92mPHP-FPM v8.3 status: $php_status (OK)\033[0m"
+                else
+                  echo -e "\033[91mPHP-FPM v8.3 status: $php_status (v8.3 is required)\033[0m"
+                  exit 1
+                fi
+
 
     Vulnerabilities:
         needs: Test-Services
